core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from shop import views
from django.views.generic import TemplateView

urlpatterns = [
    # path('', domain_redirect, name='domain_redirect'),
    path('',views.IndexView.as_view(),name='index'),
    path("shop/", include("shop.urls")),
    path('admin/', admin.site.urls),
]

# serving static and media for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/shop/urls.py
from django.urls import path, include
from . import views
from django.apps import apps


app_name = 'shop'

urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),
    path('order-items/', views.NewOrderItemsView.as_view(), name='order_items'),
    path('order-customer/<int:order_id>/', views.NewOrderCustomerView.as_view(), name='add_customer'),
    path('select-customer/<int:order_id>/<int:customer_id>/', views.SelectOrderCustomerView.as_view(), name='select_customer'),
    path('order-payment/<int:order_id>/', views.PaymentDetailView.as_view(), name='order_payment'),

   ]

core/shop/models.py
from django.db import models
from django.utils import timezone
from khayyam import JalaliDatetime

class Customer(models.Model):
	name = models.CharField(max_length=250)
	phone_number = models.CharField(max_length=11)
	address = models.CharField(max_length=1000)

	def __str__(self):
		return self.name


class Category(models.Model):
	name = models.CharField(max_length=250)

	def __str__(self):
		return self.name

class Item(models.Model):
	name = models.CharField(max_length=250)
	price = models.PositiveIntegerField(default=0)
	category = models.ForeignKey(Category, on_delete=models.CASCADE)

	def __str__(self):
		return self.name

class OrderItem(models.Model):
	order_id = models.IntegerField(default=100000)
	item = models.ForeignKey(Item, on_delete=models.CASCADE)
	count = models.PositiveIntegerField(default=0)

	def __str__(self):
		return f'{self.item.name} - {self.count}'

class Order(models.Model):
	order_id = models.IntegerField(default=100000)
	items = models.ManyToManyField(OrderItem)
	customer = models.ForeignKey(Customer, null=True, blank=True, on_delete=models.SET_NULL)
	status = models.BooleanField(default=False)
	category = models.CharField(max_length=250, null=True, blank=True)
	payment_method = models.CharField(max_length=250, null=True, blank=True)
	delivery = models.BooleanField(default=False)
	delivery_price = models.IntegerField(default=0)
	payment_status = models.BooleanField(default=False)

	created_date = models.DateTimeField(auto_now_add = True)

	def get_total_price(self):
		total_price = 0
		for item in self.items.all():
			total_price = total_price + item.price * item.count
		total_price = total_price + self.delivery_price
		return total_price

	@property
	def shamsi_created_date(self):
		return JalaliDatetime(self.created_date).strftime('%Y/%m/%d')

core/shop/forms.py
from django import forms
from .models import Item

class DynamicItemForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(DynamicItemForm, self).__init__(*args, **kwargs)
        for item in Item.objects.all():
            self.fields[f'{item.name}'] = forms.IntegerField(label=f'{item.name}')

# مثال استفاده:
# ایجاد یک فرم با 20 فیلد name

class NewCustomerForm(forms.Form):
    name = forms.CharField(required=False)
    phone_number = forms.CharField(required=False)
    address = forms.CharField(required=False)

class OrderDetailForm(forms.Form):
    category = forms.CharField()
    payment = forms.CharField()

core/shop/views.py
from django.shortcuts import render, redirect
from django.views import View
import random
from random import randint
from .models import *
from .forms import *
from django.forms import formset_factory




class IndexView(View):

	def get(self, request):

		return render(request, 'shop/index.html')

# class OrderItemsView(View):

# 	template_name = 'shop/menu.html'

# 	def get(self, request):
# 		order_id = random.randint(100000,999999)
# 		form = NewOrderItemsForm
# 		items = Item.objects.all()
# 		return render(request, self.template_name, {'form':form, 'items':items, 'order_id':order_id})

# 	def post(self, request, *args, **kwargs):
# 		form = NewOrderItemsForm(request.POST)
# 		if form.is_valid():
# 			items = Item.objects.all()
# 			order_id = form.cleaned_data['order_id']
# 			item = form.cleaned_data['item']
# 			count = form.cleaned_data['count']
# 			selected_item = Item.objects.get(name = item)
# 			new_order_item = OrderItem.objects.create(
# 				item = selected_item,
# 				count = count,
# 				order_id = order_id
# 			)
# 			return render(request, self.template_name, {'form':form, 'items':items, 'order_id':order_id, 'message':'the order is submitted'})


class NewOrderItemsView(View):
	items_count = Item.objects.all().count()

	def get(self, request, *args, **kwargs):

		form = DynamicItemForm
		items = Item.objects.all()
		return render(request, 'shop/menu.html', {'form': form,'items':items})

	def post(self, request, *args, **kwargs):
		form = DynamicItemForm(request.POST)
		order_id = random.randint(100000,999999)
		if form.is_valid():
			# print(form.cleaned_data)
			for key,value in form.cleaned_data.items():
				item = Item.objects.get(name=key)
				new_order_item = OrderItem.objects.create(
					order_id = order_id,
					item = item,
					count = value
				)
			new_order = Order.objects.create(
				order_id = order_id,
			)
			for item in OrderItem.objects.all():
				if item.order_id == order_id and item.count != 0:
					new_order.items.add(item)
			return redirect('shop:add_customer', order_id)

class NewOrderCustomerView(View):

	template_name = 'shop/add-customer.html'

	def get(self, request, order_id):
		order = Order.objects.get(order_id = order_id)
		customers = Customer.objects.all()
		form = NewCustomerForm
		return render(request, self.template_name, {'order':order, 'customers':customers, 'form':form})

	def post(self, request, order_id):
		form = NewCustomerForm(request.POST)

		if form.is_valid():
			new_customer = Customer.objects.create(
				name = form.cleaned_data['name'],
				phone_number = form.cleaned_data['phone_number'],
				address = form.cleaned_data['address']
			)
			order = Order.objects.get(order_id = order_id)
			return redirect('shop:select_customer', order_id, new_customer.id)

class SelectOrderCustomerView(View):

	def get(self, request, order_id, customer_id):
		order = Order.objects.get(order_id=order_id)
		customer = Customer.objects.get(id=customer_id)
		order.customer = customer
		order.save()
		return redirect('shop:order_payment', order_id)
	
class PaymentDetailView(View):

	template_name = 'shop/payment-detail.html'

	def get(self, request, order_id):
		form = OrderDetailForm
		return render(request, self.template_name, {'form':form})

	def post(self, request, order_id):
		order = Order.objects.get(order_id = order_id)
		form = OrderDetailForm(request.POST)
		if form.is_valid():
			print(form.cleaned_data)
			order.category = form.cleaned_data['category']
			order.payment_method = form.cleaned_data['payment']
			order.save()
			return redirect('shop:index')

core/shop/templates/shop/add-customer.html
{% load static %}
{% load humanize %}
<!doctype html>
<html dir="rtl" lang="fa-IR">

<head>

    <!-- META DATA -->
    <meta charset="UTF-8">
    <meta content='width=device-width, initial-scale=1.0, user-scalable=0' name='viewport'>
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="پلتفرم فروشگاه ساز پیکوسایت" name="description">
    <meta content="limoostudio" name="author">
    <meta content="بهترین سایت ساز ایرانی با قابلیت‌های فراوان و برنامه‌نویسی اختصاصی، همگام شده با آخرین الگوریتم‌های گوگل"
          name="keywords">

    <!-- FAVICON -->
    <link href="" rel="shortcut icon" type="image/x-icon"/>

    <!-- TITLE -->
    <title>احراز شماره تماس</title>

    <!-- BOOTSTRAP CSS -->
    <link href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}" id="style" rel="stylesheet"/>

    <!-- STYLE CSS -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/css/plugins.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/css/dark-style.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/css/transparent-style.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/skin-modes.css' %}" rel="stylesheet"/>

    <!--- FONT-ICONS CSS -->
    <link href="{% static 'assets/css/icons.css' %}" rel="stylesheet"/>

    <!-- COLOR SKIN CSS -->
    <link href="{% static 'assets/colors/color1.css' %}" id="theme" media="all" rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/switcher/css/switcher.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/switcher/demo.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/fonts/styles-fa-num/iran-yekan.css' %}" id="fonts" rel="stylesheet">
    <link href="{% static 'assets/css/rtl.css' %}" rel="stylesheet"/>
</head>

<body class="app sidebar-mini rtl login-img">

    <div class="">
        <div class="page">
            <div class="">
                <div class="col col-login mx-auto mt-7">
                    <div class="text-center">
                        <img alt="" class="header-brand-img m-0" src="{{ store.get_logo_image }}" height="85px">
                    </div>
                </div>
                <div class="container-login100">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card">
                                <div class="card-header">
                                    <div class="card-title">افزودن مشتری جدید</div>
                                </div>
                                <form method="post" action="{% url 'shop:add_customer' order.order_id %}">
                                    {% csrf_token %}
                        
                                    <div class="card-body">
                                        <div class="form-row">
                                            <div class="form-group col-md-6 mb-0">
                                                <div class="form-group">
                                                    <input name="name" class="form-control" id="city" placeholder="نام" type="text">
                                                </div>
                                            </div>
                                            <div class="form-group col-md-6 mb-0">
                                                <div class="form-group">
                                                    <input name="phone_number" class="form-control" id="postal" placeholder="شماره تماس"
                                                           type="text">
                                                </div>
                                            </div>
                                            <div class="form-group col-md-12 mb-0">
                                                <div class="form-group">
                                                    <input name="address" class="form-control" id="postal" placeholder="آدرس"
                                                           type="text">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-footer mt-2">
                                            <button type="submit" class="login100-form-btn btn-primary">افزودن مشتری جدید</button>
                                        </div>
                                        <div><br></div>
                                    </div>
                                </form>
                        
                                    <div class="card-header">
                                            <h3 class="card-title">انتخاب از مشتریان سابق</h3>
                                    </div>
                                    <div class="card-body">
                                        <div class="table-responsive">
                                            <table class="table table-bordered table-vcenter">
                                                <thead>
                                                <tr class="border-top">
                                                    <th>نام</th>
                                                    <th>شماره تماس</th>                                                   
                                                    <th>آدرس</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                    {% for customer in customers %}
                                                        <tr>
                                                            <td><a href="{% url 'shop:select_customer' order.order_id customer.id %}">{{customer.name}}</a></td>
                                                            <td>{{customer.phone_number}}</td>
                                                            <td>{{customer.address}}</td>
                                                        </tr>
                                                    {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                        
                                    
                                    
                        
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<!-- JQUERY JS -->
<script src="{% static 'assets/js/jquery.min.js' %}"></script>

<!-- BOOTSTRAP JS -->
<script src="{% static 'assets/plugins/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- SHOW PASSWORD JS -->
<script src="{% static 'assets/js/show-password.min.js' %}"></script>

<!-- Perfect SCROLLBAR JS-->
<script src="{% static 'assets/plugins/p-scroll/perfect-scrollbar.js' %}"></script>

<!-- Color Theme js -->
<script src="{% static 'assets/js/themeColors.js' %}"></script>

<!-- CUSTOM JS -->
<script src="{% static 'assets/js/custom.js' %}"></script>

<!-- Custom-switcher -->
<script src="{% static 'assets/js/custom-swicher.js' %}"></script>

<!-- Switcher js -->
<script src="{% static 'assets/switcher/js/switcher.js' %}"></script>

<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/sticky.js' %}"></script>
<script src="{% static 'assets/plugins/sidemenu/sidemenu.js' %}"></script>
<script src="{% static 'assets/plugins/sidebar/sidebar.js' %}"></script>
<script src="{% static 'assets/js/custom-swicher.js' %}"></script>
<script src="{% static 'assets/js/themeColors.js' %}"></script>
<script src="{% static 'assets/js/widget.js' %}"></script>
<script src="{% static 'assets/plugins/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/custom.js' %}"></script>
<script src="{% static 'assets/js/handlecounter.js' %}"></script>

</body>


</html>

core/shop/templates/shop/index.html
{% load static %}
<!doctype html>
<html dir="rtl" lang="fa-IR">

<head>

    <!-- META DATA -->
    <meta charset="UTF-8">
    <meta content='width=device-width, initial-scale=1.0, user-scalable=0' name='viewport'>
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="پلتفرم فروشگاه ساز پیکوسایت" name="description">
    <meta content="limoostudio" name="author">
    <meta content="بهترین سایت ساز ایرانی با قابلیت‌های فراوان و برنامه‌نویسی اختصاصی، همگام شده با آخرین الگوریتم‌های گوگل"
          name="keywords">

    <!-- FAVICON -->
    <link href="" rel="shortcut icon" type="image/x-icon"/>

    <!-- TITLE -->
    <title>احراز شماره تماس</title>

    <!-- BOOTSTRAP CSS -->
    <link href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}" id="style" rel="stylesheet"/>

    <!-- STYLE CSS -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/css/plugins.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/css/dark-style.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/css/transparent-style.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/skin-modes.css' %}" rel="stylesheet"/>

    <!--- FONT-ICONS CSS -->
    <link href="{% static 'assets/css/icons.css' %}" rel="stylesheet"/>

    <!-- COLOR SKIN CSS -->
    <link href="{% static 'assets/colors/color1.css' %}" id="theme" media="all" rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/switcher/css/switcher.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/switcher/demo.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/fonts/styles-fa-num/iran-yekan.css' %}" id="fonts" rel="stylesheet">
    <link href="{% static 'assets/css/rtl.css' %}" rel="stylesheet"/>
</head>

<body class="app sidebar-mini rtl login-img">

<div class="">
    <div class="page">
        <div class="">
            <div class="row p-7 m-5">
                <div class="col-md-6 col-xl-6 text-center">
                    <a class="btn btn-primary d-grid p-5 m-5" href="javascript:void(0)">ایجاد سفارش جدید</a>
                </div>
                <div class="col-md-6 col-xl-6 text-center">
                    <a class="btn btn-primary d-grid p-5 m-5" href="javascript:void(0)">ایجاد هزینه جدید</a>
                </div>
                <div class="col-md-6 col-xl-6 text-center">
                    <a class="btn btn-primary d-grid p-5 m-5" href="javascript:void(0)">لیست سفارشات</a>
                </div>
                <div class="col-md-6 col-xl-6 text-center">
                    <a class="btn btn-primary d-grid p-5 m-5" href="javascript:void(0)">سوابق مالی</a>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- JQUERY JS -->
<script src="{% static 'assets/js/jquery.min.js' %}"></script>

<!-- BOOTSTRAP JS -->
<script src="{% static 'assets/plugins/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- SHOW PASSWORD JS -->
<script src="{% static 'assets/js/show-password.min.js' %}"></script>

<!-- Perfect SCROLLBAR JS-->
<script src="{% static 'assets/plugins/p-scroll/perfect-scrollbar.js' %}"></script>

<!-- Color Theme js -->
<script src="{% static 'assets/js/themeColors.js' %}"></script>

<!-- CUSTOM JS -->
<script src="{% static 'assets/js/custom.js' %}"></script>

<!-- Custom-switcher -->
<script src="{% static 'assets/js/custom-swicher.js' %}"></script>

<!-- Switcher js -->
<script src="{% static 'assets/switcher/js/switcher.js' %}"></script>

</body>


</html>

core/shop/templates/shop/menu.html
{% load static %}
{% load humanize %}
<!doctype html>
<html dir="rtl" lang="fa-IR">

<head>

    <!-- META DATA -->
    <meta charset="UTF-8">
    <meta content='width=device-width, initial-scale=1.0, user-scalable=0' name='viewport'>
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="پلتفرم فروشگاه ساز پیکوسایت" name="description">
    <meta content="limoostudio" name="author">
    <meta content="بهترین سایت ساز ایرانی با قابلیت‌های فراوان و برنامه‌نویسی اختصاصی، همگام شده با آخرین الگوریتم‌های گوگل"
          name="keywords">

    <!-- FAVICON -->
    <link href="" rel="shortcut icon" type="image/x-icon"/>

    <!-- TITLE -->
    <title>احراز شماره تماس</title>

    <!-- BOOTSTRAP CSS -->
    <link href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}" id="style" rel="stylesheet"/>

    <!-- STYLE CSS -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/css/plugins.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/css/dark-style.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/css/transparent-style.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/skin-modes.css' %}" rel="stylesheet"/>

    <!--- FONT-ICONS CSS -->
    <link href="{% static 'assets/css/icons.css' %}" rel="stylesheet"/>

    <!-- COLOR SKIN CSS -->
    <link href="{% static 'assets/colors/color1.css' %}" id="theme" media="all" rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/switcher/css/switcher.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/switcher/demo.css' %}" rel="stylesheet"/>
    <link href="{% static 'assets/fonts/styles-fa-num/iran-yekan.css' %}" id="fonts" rel="stylesheet">
    <link href="{% static 'assets/css/rtl.css' %}" rel="stylesheet"/>
</head>

<body class="app sidebar-mini rtl login-img">

    <div class="">
        <div class="page">
            <div class="">
                <div class="col col-login mx-auto mt-7">
                    <div class="text-center">
                        <img alt="" class="header-brand-img m-0" src="{{ store.get_logo_image }}" height="85px">
                    </div>
                </div>
                <div class="container-login100">
                    <div class="wrap-login100 p-6">
                        <span class="login100-form-title">لیست آیتم‌های موجود</span>
                        <div class="table-responsive">
                            <form method="post" action="{% url 'shop:order_items' %}" enctype="multipart/form-data"> 
                                <table class="table table-bordered" >
                                {% csrf_token %}
                                <thead>
                                    <tr>
                                        <th>عنوان<span class="text text-white"></span></th>
                                        <th>قیمت<span class="text text-white"></span></th>                  
                                        <th>تعداد<span class="text text-white"></span></th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for field in form %}
                                <tr>
                                    <td class="align-middle">{{ field.label }}</td>
                                    <td class="align-middle">
                                        {% for item in items %}
                                            {% if item.name == field.label %}
                                            {{ item.price|intcomma }} تومان
                                            {% endif %}
                                        {% endfor %}
                                    </td>
                                    <td>
                                        <div class="handle-counter" id="handleCounter4">
                                            <button class="counter-minus btn btn-white lh-2 shadow-none"
                                                    type="button">
                                                <i class="fa fa-minus text-muted"></i>
                                            </button>
                                            <input name="{{ field.label }}" class="qty" type="number" value="0">
                                            <button class="counter-plus btn btn-white lh-2 shadow-none"
                                                    type="button">
                                                <i class="fa fa-plus text-muted"></i>
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}
                                </tbody>
                                </table>
                               
                          
                            <input type="submit" value="Submit">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<!-- JQUERY JS -->
<script src="{% static 'assets/js/jquery.min.js' %}"></script>

<!-- BOOTSTRAP JS -->
<script src="{% static 'assets/plugins/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- SHOW PASSWORD JS -->
<script src="{% static 'assets/js/show-password.min.js' %}"></script>

<!-- Perfect SCROLLBAR JS-->
<script src="{% static 'assets/plugins/p-scroll/perfect-scrollbar.js' %}"></script>

<!-- Color Theme js -->
<script src="{% static 'assets/js/themeColors.js' %}"></script>

<!-- CUSTOM JS -->
<script src="{% static 'assets/js/custom.js' %}"></script>

<!-- Custom-switcher -->
<script src="{% static 'assets/js/custom-swicher.js' %}"></script>

<!-- Switcher js -->
<script src="{% static 'assets/switcher/js/switcher.js' %}"></script>

<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/sticky.js' %}"></script>
<script src="{% static 'assets/plugins/sidemenu/sidemenu.js' %}"></script>
<script src="{% static 'assets/plugins/sidebar/sidebar.js' %}"></script>
<script src="{% static 'assets/js/custom-swicher.js' %}"></script>
<script src="{% static 'assets/js/themeColors.js' %}"></script>
<script src="{% static 'assets/js/widget.js' %}"></script>
<script src="{% static 'assets/plugins/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/custom.js' %}"></script>
<script src="{% static 'assets/js/handlecounter.js' %}"></script>

</body>


</html>